version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: doebrasil
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"